### ISSUE TITLE
Issue with setTranform in textArea

### ISSUE THREAD

**Issue by kirankn8** [rivo/tview#1014]
@rivo I am trying to write a custom input handler which handles sensitive information, the setTranform function is not public due to which I am unable to utilize the functionality to mask sensitive information. 
https://github.com/rivo/tview/blob/65571ae51e71d29a5e8a0082667b778939cca29f/textarea.go#L1607C20-L1607C32

Could you please fix it

**Comment by rivo** [comment]
That's what `InputField` and its [`SetMaskCharacter()`](https://pkg.go.dev/github.com/rivo/tview#InputField.SetMaskCharacter) function is for.

**Comment by kirankn8** [comment]
yes @rivo , but when I write a custom input handler similar to the InputField by overriding the Draw function, the textArea does not expose setTranform function.

**Comment by rivo** [comment]
I don't plan on making `setTransform` public. It's a hack to make password masking work in `InputField`s. But it's not a functionality that `TextArea` needs IMHO. In the grander scheme of things, `TextArea` might benefit from a way to format text, e.g. for colour coding, line numbers, or auto-formatting. But that's a huge undertaking and `setTransform` will not fit the bill, it will likely be removed at that point (which I can't if it's public). I haven't even begun to think about this.

I don't know what your "custom design/logic" is but I would suggest you build on top of `InputField` instead of `TextArea`. If you want to describe your customizations, I might be able to give you some pointers.

**Comment by kirankn8** [comment]
ok, understood. one of my requirement is I want to change the appearance of the input field from the box look (as seen in your examples https://github.com/rivo/tview/wiki/InputField) to something like this `label : [                    ]`. How could I approach this

**Comment by kirankn8** [comment]
Nvm, I think I figured it out how to go about this. thank you for your quick response. I am closing this ticket.
