### ISSUE TITLE
Feature Request: Add ability to use the left and right arrow keys in inputFields

### ISSUE THREAD

**Issue by joegrasse** [rivo/tview#103]
It would be nicer if the user could use the left and right arrow keys within a form inputField to correct mistypes.

**Comment by rivo** [comment]
I'm giving this the "on roadmap" label. I'm planning to add this.

Can't say exactly when but hopefully soon.

**Comment by rivo** [comment]
The latest commit introduces free movement within input fields. This was an effort of many hours, much more than what I had anticipated. The reason is mostly Unicode support, in which one character can consist of multiple runes (with modifiers, zero-width joiners etc.) and one rune can occupy multiple bytes in a string. Additionally, the width of a character can be more than one cell on the screen. All of this needs to be handled properly.

To navigate the input field, I took cues from Bash:

- __Left arrow:__ Move left by one character.
- __Right arrow:__ Move right by one character.
- __Home, Ctrl-A, Alt-a:__ Move to the beginning of the line.
- __End, Ctrl-E, Alt-e:__ Move to the end of the line.
- __Alt-left, Alt-b:__ Move left by one word.
- __Alt-right, Alt-f:__ Move right by one word.
- __Backspace:__ Delete the character before the cursor.
- __Delete:__ Delete the character after the cursor.
- __Ctrl-K:__ Delete from the cursor to the end of the line.
- __Ctrl-W:__ Delete the last word before the cursor.
- __Ctrl-U:__ Delete the entire line.

If you find any undesirable behaviour, please open an issue.

**Comment by joegrasse** [comment]
Thank you very much for your work on this!
