### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by andrewuhl** [rivo/tview#11]
Any plans / scope in this project to add basic plotting widgets? E.g. scatter, line or bar plots?

**Comment by rivo** [comment]
I'm not sure. I find that [github.com/gizak/termui](https://github.com/gizak/termui) does a pretty good job at that. I was trying to focus on things that `termui` doesn't cover.

I'm not ruling it out at this point but plots/charts would more likely be on the long-term roadmap.

Is there a specific reason you'd like to have it in here instead of using `termui`?

**Comment by andrewuhl** [comment]
```termui``` was the inspiration for my question. Is it possible to embed a ```termui``` component in one of your flex panels? I haven't tried this yet, but perhaps an integration is straightforward?

**Comment by rivo** [comment]
I had a quick look at how `termui` works. I'm by no means an expert on `termui` internals but it looks like they draw their charts into buffers whose content then gets copied over to [github.com/nsf/termbox-go](https://github.com/nsf/termbox-go). `tview`is not based on `termbox` but on `tcell` but `termui` looks losely coupled enough to be connected to something different.

My guess is that instead of calling their [render()](https://github.com/gizak/termui/blob/e9a3a6b3d6472ce875254d734f36335c15ebd4e6/render.go#L101) function, you could create your own primitive in `tview` whose [Draw()](https://godoc.org/github.com/rivo/tview#Primitive) function would read out the `termui` plot buffer and draw it into `tview`'s screen.

But like I said, this is just a guess based on a very brief look.

**Comment by darkhz** [comment]
Line charts has now been implemented in [tvxwidgets](https://github.com/navidys/tvxwidgets), import and use.
