### ISSUE TITLE
Please tag releases with git tags

### ISSUE THREAD

**Issue by skovtunenko** [rivo/tview#116]
Thank you for a great tui!
Having human-readable **change list** is great, but can you tag your code with **git tags** also?
Thanks!

**Comment by rivo** [comment]
How would you use those tags? Why are they needed?

**Comment by skovtunenko** [comment]
@rivo , for now this is the simplest way to help with reproducible builds. Go vendoring tools and the most popular tool **dep** capable to get the sources from specified **git tag**.
Here is more details about semver tags:
https://golang.github.io/dep/docs/Gopkg.toml.html#version

With every commit, you can break public API and if someone relies on your API, then having tags can help to download some concrete compatible version of your beautiful library.

**Comment by rivo** [comment]
I know semver tags and I understand how they are commonly used. Maybe I wasn't very specific with my question. I would like to understand where _you specifically_ had a problem with `tview` and missing tags.

I have two comments about this:

- I try very hard not to break the public API. This goes so far as to even refusing some requests because implementing them would break the API. There have been a few breaks in the beginning of this (five month old) project but newer features/changes should be additions, not breaking changes.
- Every commit in this project is either a bugfix or some improvement. By the semver logic, I'd have to add a tag for each commit. I'd like to save myself that effort. (And to be honest, I know I will forget it anyway. The reason I haven't used git tags because I forgot to add them frequently.) I know [the `revision` parameter](https://golang.github.io/dep/docs/Gopkg.toml.html#revision) is frowned upon but it is there so it won't keep you from putting `tview` into `dep`.

But I'd like to hear if someone has had problems with backwards compatibility or similar issues. If my workflow is giving you serious problems in your project, we should definitely discuss.

**Comment by rivo** [comment]
Will reopen when there's more information.

**Comment by vladimirvivien** [comment]
Can this be reopen? I appreciate the fact that you work hard to ensure the API is backward compatible.  I really like tview's simple and well-designed API.  

However, would you consider tagging at least 1 previous version for the following reasons
- Go modules (1.11+) encourages tagging/sem-versioning for reproducible builds (in time)
- As an adopter of this project, knowing that there are stable snapshots is a good reassurance that builds can be reproduced regardless of what is happening in HEAD.

At the very least, would you consider creating some branches ?

Thank you.

**Comment by rivo** [comment]
Please have a look at #169. I'm planning to introduce this once modules are official.
