### ISSUE TITLE
Feature request: Mouse support

### ISSUE THREAD

**Issue by pjebs** [rivo/tview#13]

**Comment by pomke** [comment]
How would you like this to look? 

```go
func (b *Box) SetMouseCapture(capture func(event *tcell.EventMouse) *tcell.EventMouse) *Box
```

**Comment by rivo** [comment]
There will be probably something like this. But mouse support should be much more than that. If I click on an input field, it should receive focus and allow me to edit it. If I click on a button, it should be activated. Any primitive should receive focus when clicked on. Things like that.

It's a higher effort, which is why I haven't gotten around to implementing it yet.

**Comment by markx** [comment]
It'll be nice to setup some ground work like a basic or even empty handler, so we can easily implement the function locally before there's global support for all primitives.

**Comment by diamondburned** [comment]
@markx check out @Bios-Marcel's https://github.com/Bios-Marcel/tview/ repository. Perhaps you could cherry-pick some commits into a PR 👀

**Comment by Bios-Marcel** [comment]
Duh, now I gotta talk about this.

My mouse support isn't ~~well~~fully implemented:

* It breaks terminal selection
* No focus on click (you gotta add that for yourself if you want it)
* Only `Button` and `List` handle clicks by default
* Scrolling isn't handled

**Comment by antonmedv** [comment]
Hi @rivo,

Any plans add this feature? :)

**Comment by rivo** [comment]
Mouse support has been added. Please have a look and let me know in case you find any bugs.
