### ISSUE TITLE
How to force redraw primitives?

### ISSUE THREAD

**Issue by kovart** [rivo/tview#143]
Does the lib updates only if the keyboard input is captured?
What about self-updatable primitives?

**Comment by rivo** [comment]
`Application.Draw()` is called in response to a keyboard event because keyboard events typically lead to display changes.

If you make changes to a primitive independently, and especially in separate goroutines, you'll need to call `Application.Draw()` yourself. Some primitives give you tools to inform you that something has changed, for example [the `TextView` "changed" event](https://godoc.org/github.com/rivo/tview#TextView.SetChangedFunc).

Let me know if this answers your question.

**Comment by kovart** [comment]
Yep. But, It could be better to call Draw method for specific primitive, or not?

**Comment by rivo** [comment]
It seems that way at first but (most of the time) it's not. There's a longer discussion in #128 which you'll want to read. Feel free to add to that discussion if you have valuable input.

I'll close this issue but will reopen if it turns out it's still an open item.
