### ISSUE TITLE
Adopt GO 1.11 Modules Versioning

### ISSUE THREAD

**Issue by mapl** [rivo/tview#169]
It would be nice to have some proper versioning for tview.

https://github.com/golang/go/wiki/Modules#new-concepts

**Comment by rivo** [comment]
Support for modules is still preliminary and experimental in 1.11. Once it becomes official (most likely 1.12), I will very likely add support for it in this project (including versioning which, sigh, I suppose I won't be able to dodge). I'm waiting because things in the dependency management department have changed a lot (for a while, `go dep` was hailed as the future). So I'm waiting for the official and final word on this.

We've had a related discussion before, please see #116 and #53.
