### ISSUE TITLE
List.GetRect() gives incorrect size

### ISSUE THREAD

**Issue by delaneyj** [rivo/tview#194]
```Go
list := tview.NewList().
  AddItem("Quit", "Press to exit", 'q', nil)
x, y, w, h := list.GetRect()
log.Printf("just quit: %d,%d %dx%d", x, y, w, h)
```
Shows `just quit: 0,0 15x10`.  It appears 15 width and 10 height are defaults of box object and don't match actual rendered size of box (in this case 2 for the height)

**Comment by rivo** [comment]
Yes, this is correct. When you call `tview.NewList()`, the list is created with its default size. If you call `list.GetRect()` immediately afterwards, as you do, you will receive that size.

There are some functions which modify a primitive's size, for example `Application.SetRoot(list, true)` or any of the layout classes (`Flex`, `Grid`). When you call `list.GetRect()` after it was modified by these functions, you will get a different size and it should be the size that you see on screen.

Let me know if this clarifies it.

**Comment by delaneyj** [comment]
Well I'm using a List inside a Flex but the Rect is still 15x10.

**Comment by rivo** [comment]
It gets updated when it's drawn, not when it's added. Because the actual screen size is known only at drawing time and most primitives such as `Flex` depend on the actual screen size. Thus, the final positions and sizes of primitives get calculated only when they are drawn.

Maybe you want to let me know where this gives you problems so I can suggest a solution.

**Comment by rivo** [comment]
Will reopen when there's new information that requires action.

**Comment by mrusme** [comment]
I'm reopening this because I'm experiencing a similar issue. I have a TextView which is set as root of the application when the program starts. Hence it's being displayed right from the beginning. I have a function that is being triggered upon user input (which happens after the initial draw), that uses Box.GetRect() of the TextView. The width is correct, however, the height is always only around 50% of the actual box height and I can't seem to find a solution to this.

Any help here would be appreciated!

**Comment by rivo** [comment]
There was another comment here which I can't see anymore. Please comment/reopen/open a new issue if there's anything I should look at.
