### ISSUE TITLE
undefined: runewidth.ZeroWidthJoiner

### ISSUE THREAD

**Issue by prologic** [rivo/tview#205]
I belive something you are depending on has changed and broken compat somehow

```
$ go build .
# github.com/rivo/tview
../go/pkg/mod/github.com/rivo/tview@v0.0.0-20181214165719-f93fbad8f897/util.go:55:2: undefined: runewidth.ZeroWidthJoiner

```

#189 did seem similar at first but I'm not sure it's the same issue?

**Comment by prologic** [comment]
```
$ cat go.mod
module github.com/prologic/chat

require (
	github.com/gdamore/encoding v0.0.0-20151215212835-b23993cbb635 // indirect
	github.com/gdamore/tcell v1.1.0
	github.com/gopherjs/gopherjs v0.0.0-20181103185306-d547d1d9531e // indirect
	github.com/jtolds/gls v4.2.1+incompatible // indirect
	github.com/lucasb-eyer/go-colorful v0.0.0-20181028223441-12d3b2882a08 // indirect
	github.com/mattn/go-runewidth v0.0.3 // indirect
	github.com/rivo/tview v0.0.0-20181214165719-f93fbad8f897
	github.com/smartystreets/assertions v0.0.0-20180927180507-b2de0cb4f26d // indirect
	github.com/smartystreets/goconvey v0.0.0-20181108003508-044398e4856c // indirect
	golang.org/x/text v0.3.0 // indirect
	gopkg.in/DATA-DOG/go-sqlmock.v1 v1.3.0 // indirect
)
```

**Comment by rivo** [comment]
It certainly looks like the same issue as #189. The latest version of [`mattn/runewidth`](https://github.com/mattn/go-runewidth/) has `ZeroWidthJoiner` defined, see [here](https://github.com/mattn/go-runewidth/blob/3ee7d812e62a0804a7d0a324e0249ca2db3476d3/runewidth.go#L12). Looks like it's not in v0.0.3 yet, though.

If you upgrade `runewidth` to the latest commit, it should work.

On another note, as mentioned elsewhere already, I will introduce modules and versioning when Go v1.12 is out. But in this case, since @mattn hasn't tagged the latest version yet, if I wanted to use tags instead of commit hashes, I'd have to wait quite long to incorporate his change into my package. People have asked for version numbers quite often here but what it likely comes down to is that many users will have outdated versions of the package.

Anyway, my comment is not related to this issue so you can ignore it. ;-)

Let me know if you could get it to work.

**Comment by prologic** [comment]
Yeah I'm actually using `go mod` here myself and have already "tried"
upgrading the mentioned dep to no avail. I haven't dug any further atm.

James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by mattn** [comment]
I tagged v0.0.4 just now.

**Comment by prologic** [comment]
Thanks I'll give it a whirl soon!

James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by uchobby** [comment]
Just tried to "go get" and got the error.  looks like it's not fixed.  What can I do?

C:\Users\<username>\go\src\github.com\gdamore\tcell\_demos>go get github.com/rivo/tview
# github.com/rivo/tview
..\..\..\rivo\tview\util.go:56:2: undefined: runewidth.ZeroWidthJoiner

**Comment by rivo** [comment]
@uchobby, are you using go modules? `tview`'s `go.mod` file specifies `0.0.4` for `mattn/go-runewidth` which should include the `ZeroWidthJoiner` variable. Make sure that you're using that version.
