### ISSUE TITLE
Watch for additional keys for making cell, row or column selection

### ISSUE THREAD

**Issue by andrewuhl** [rivo/tview#22]
Currently, table watches for ENTER key press to enter the table for selection of cell/row/column. It would be useful to have an additional key (or keys) watched so that, e.g., one key could be captured to make a full row selection, while different (possibly user-defined) key(s) could be captured to make a full column selection: E.g.

```go
table.Select(0, 0).SetFixed(1, 1).SetDoneFunc(func(key tcell.Key) {
		if key == tcell.KeyEscape {
			table.SetSelectable(false, false)
		} else if key == tcell.KeyEnter { // select row
			table.SetSelectable(true, false)
		} else if key == tcell.KeyBackspace { // select column, requires changes to table.go
			table.SetSelectable(false, true)
		}
	})
```

**Comment by rivo** [comment]
Sorry for the late response. I had to think about this a bit. And this was related to an internal todo I've had in mind for a while. Many primitives offer a default key handling, e.g. the `TextView` allows you to navigate the view's content in a Vim-like fashion. This may not be what you want so you should be able to change that handling or install a custom key event handler for additional functionality (like you suggested).

The `Box` primitive now has a function `SetInputCapture()` which allows you to intercept any key events sent to a primitive. Because `Box` is the superclass of all other primitives, this is available to all of them.

Btw, The same function also exists for `Application`, allowing you to intercept *all* key events. (This was previously `SetKeyCapture()` which has been removed in favour of this new function.)

Anyway, using those new functions, you should be able to achieve what you described.
