### ISSUE TITLE
Feature request: add columns of fixed width

### ISSUE THREAD

**Issue by Sacules** [rivo/tview#227]
Hello, I'm loving tview and using it to build a small [music tagger](https://gitlab.com/Sacules/index). I'd like to ask something similar to #119: I have a table of content and I'd like to assign a fixed width to each column (with the possibility of resizing them on the fly), and wrapping the text that doesn't fit, or displaying "..." at the end of it.

**Comment by dguendisch** [comment]
That's at least possible on cell level, see https://github.com/rivo/tview/blob/master/table.go#L74
Just give all your cells in a column the respective maxWidth and tview will append a nice `…` for every cell text exceeding the maxWidth, effectively limiting your column width.
Haven't seen a way though on how to specify this on a table or column level (instead of every single cell), but haven't looked deeply for such.

**Comment by rivo** [comment]
Thanks to @dguendisch for providing the correct answer here.

@Sacules, let us know if this solves your problem.

**Comment by Sacules** [comment]
Yeah it works by now, thanks!

**Comment by jsumners-nr** [comment]
For those looking at this in the future, the static link is https://github.com/rivo/tview/blob/e5e361b9d7908c94aa426e31c208e2c69df0d95d/table.go#L74
