### ISSUE TITLE
Support escape sequences

### ISSUE THREAD

**Issue by maja42** [rivo/tview#24]
I'm using the io.Writer interface from the TextView and directly feed the stdout/stderr output from another application, which is started via the io.exec package.

This application prints standard linux escape sequences to change the text color. However, tview does not interpret this escape sequences and prints them as standard ascii characters.

Is it possible to use ansi escape sequences to define colors, or convert them to the appropiate color strings automatically?

**Comment by rivo** [comment]
To my knowledge, I can't just write escape sequences to `tcell`. It always wants a `tcell.Color`. I do have color tags in the `TextView` such as `[red]` or `[#ff00ff]`. I decided to do this instead of escape sequences (like `gocui`) because it allows me to add color easily without having to google all the cryptic codes needed to change a color.

For your application, you could implement a `io.Writer` which translates escape sequences to these color tags. I might include something like that in the package at some point (can't tell you when, though).

**Comment by rivo** [comment]
As a heads up, `tview` now has functions that can translate ANSII escape codes to color tags. The Wiki also has an example for how colorized output from other programs can be piped into `tview`: https://github.com/rivo/tview/wiki/ANSII
