### ISSUE TITLE
Backslash not accepted in InputField

### ISSUE THREAD

**Issue by helmi77** [rivo/tview#240]
It seems the Inputfield does not allow backslashes (`\`). I've tried entering one directly, using Alt-keycodes or pasting it in, but to no avail. Is this intended?

Edit: Same goes for square and curly brackets.

**Comment by dguendisch** [comment]
Works fine for me (backslash, curly braces, etc). Maybe you have an AcceptanceFunction defined like e.g. https://github.com/rivo/tview/blob/master/demos/inputfield/main.go#L15?

**Comment by helmi77** [comment]
I just checked it again, interestingly it works on Linux, but not on Windows.

**Comment by dguendisch** [comment]
I'm on mac, so that seems to work as well.

**Comment by rivo** [comment]
Sorry for taking so long. I needed access to a Windows machine to reproduce it.

I believe this is now fixed. The problem was with the Alt key which prevented characters from being processed. Probably only users with German keyboards would have noticed this since the backslash (but also square and curly brackets) require hitting the "AltGr" key.

Fun fact: "AltGr" stands for "alternate graphic" and we can thank IBM for making us awkwardly bend our fingers to enter such common characters as `[`, `]`, `{`, `}`, or `\`. (And it's even worse on Macs where those characters are not even printed on the keyboard. I pity the one-handed person who has to enter a backslash character on a German Mac keyboard.)
