### ISSUE TITLE
Tablecells incorrectly expand in width

### ISSUE THREAD

**Issue by Bios-Marcel** [rivo/tview#242]
I have a table containing 3 columns, each having `Expand` set to `1`. However, when putting a longer text into the cell, it just expands, even though there is still enough space left.

![Table incorrectly expanding](https://user-images.githubusercontent.com/19377618/53292473-2a56e900-37c3-11e9-888f-6ffd96b00ba8.gif)

**Comment by rivo** [comment]
Yes, this would be expected. The `Expansion` value distributes "remaining available space" so that narrow tables can fill the entire available width. If you add a long text to a column, the table's remaining space becomes less. Thus, there's less to distribute to other columns.

In this example, you may want to set the `Expansion` value to `0` for the first two columns.

**Comment by Bios-Marcel** [comment]
As far as I get it, setting the expansion on all cells to the same value, they should all take an equal amount of space.

**Comment by rivo** [comment]
I think what you want is a `SetWidth()` function (relative or absolute), not a `SetExpansion()` function.

Again, `Expansion` determines how the table grows, not the initial width of a column.

**Comment by Bios-Marcel** [comment]
So, shouldn't it be a `bool` instead? Because currently it is an `int`.

**Comment by rivo** [comment]
You mean the `Expansion` value? I'm not sure what you mean.

**Comment by Bios-Marcel** [comment]
Okay, I am a bit confused.

https://github.com/rivo/tview/blob/03d744dee35eb7cd4f59bf139745bff07412b759/table.go#L83

I have had 3 columns all having their `Expansion` value set to `1`, meaning they were all equal, so why when chaing the `Text` attribute of one of those three columns, did it expand?

**Comment by rivo** [comment]
This is the function description:

> SetExpansion sets the value by which the column of this cell expands if the available width for the table is more than the table width (prior to applying this expansion value). This is a proportional value. The amount of unused horizontal space is divided into widths to be added to each column. How much extra width a column receives depends on the expansion value: A value of 0 (the default) will not cause the column to increase in width. Other values are proportional, e.g. a value of 2 will cause a column to grow by twice the amount of a column with a value of 1.

Again, the `Expansion` value does *not* determine the designated width of the column. It only grows it after the column width has already been established.

The algorithm works somewhat like this:

1. For each column `i`, calculate `column width(i) = max(text width)` over all rows.
1. Calculate `table width = sum(column width)` over all columns.
1. If `table width < available width`, distribute `available width - table width` according to `expansion` values: `column width(i) += expansion(i) * (available width - table width) / sum(expansion)`
1. If `table width >= available width`, do nothing.

This is *not* the same as, say, [`Grid.SetColumns(-1,-1,-1)`](https://godoc.org/github.com/rivo/tview#Grid.SetColumns). If it was, I would have given it a different name, as "to expand" generally means "to grow".

Thus, because of Step 1, it all depends on the width of your text. If you change it, everything changes.

I'm guessing a solution to what you're asking for is described in #184.

**Comment by Bios-Marcel** [comment]
I see. Thanks a lot man! I'll be closing the issue then.
