### ISSUE TITLE
Change textview's text on key press.

### ISSUE THREAD

**Issue by electronicous** [rivo/tview#249]
Sorry to be asking a question like this but i'm running in circles on how to do this.

I need to trigger the redraw of a textview on a keypress and have the "mode" change from one to another on each F1 keypress and have the text in textview update accordingly but i don't know what's the issue i'm facing.

Also I'm wondering can I set a minimum width for a table cell?

Here's my code

```
package main

import (
	"github.com/gdamore/tcell"
	"github.com/rivo/tview"
)

// Switch modes on keypress
var mode string = "Mode_1"
func switchmode() {
	if mode == "Mode_1" {
		mode = "Mode_2"
	} else if mode == "Mode_2" {
		mode = "Mode_1"
	}
}

func main(){
	app := tview.NewApplication()
	// Layout the widgets
	grid := tview.NewGrid().
			SetBorders(true)

	// New textview
	textview := tview.NewTextView().
		SetDynamicColors(true).
		SetRegions(true).
		SetWordWrap(true).
		SetTextAlign(tview.AlignCenter).
		SetText(mode)
	textview.SetBackgroundColor(tcell.ColorDefault)

	app.SetInputCapture(func(event *tcell.EventKey) *tcell.EventKey {
		k := event.Key()
		if k == tcell.KeyF1 {
			switchmode()
		}
		app.QueueUpdateDraw(func(){
			textview.SetText(mode)
			})
		return event
	})

	// Position
	grid.AddItem(textview, 0, 0, 1, 17, 1, 12, false)

	// Error handling
	if err := tview.NewApplication().SetRoot(grid, true).SetFocus(grid).Run(); err != nil {
		panic(err)
	}

}
```

**Comment by rivo** [comment]
Your key capture function doesn't fire because your `app` object is not used to run the application. At the end of your program, you instantiate a new `Application` object. It should look like this, however:

```go
if err := app.SetRoot(grid, true).SetFocus(grid).Run(); err != nil {
	panic(err)
}
```

You also don't need to call `QueueUpdateDraw()` from within the `SetInputCapture()` function. It is called implicitly. (See the [Wiki](https://github.com/rivo/tview/wiki/Concurrency#event-handlers) for more information.)

So it could like something like this:

```go
package main

import (
	"github.com/gdamore/tcell"
	"github.com/rivo/tview"
)

// Switch modes on keypress
var mode = "Mode_1"

func switchmode(textview *tview.TextView) {
	if mode == "Mode_1" {
		mode = "Mode_2"
	} else if mode == "Mode_2" {
		mode = "Mode_1"
	}
	textview.SetText(mode)
}

func main() {
	app := tview.NewApplication()

	// Layout the widgets
	grid := tview.NewGrid().
		SetBorders(true)

	// New textview
	textview := tview.NewTextView().
		SetDynamicColors(true).
		SetRegions(true).
		SetWordWrap(true).
		SetTextAlign(tview.AlignCenter).
		SetText(mode)
	textview.SetBackgroundColor(tcell.ColorDefault)

	app.SetInputCapture(func(event *tcell.EventKey) *tcell.EventKey {
		k := event.Key()
		if k == tcell.KeyF1 {
			switchmode(textview)
		}
		return event
	})

	// Position
	grid.AddItem(textview, 0, 0, 1, 17, 1, 12, false)

	// Error handling
	if err := app.SetRoot(grid, true).SetFocus(grid).Run(); err != nil {
		panic(err)
	}

}
```

Let me know if this answers your question.

**Comment by electronicous** [comment]
I still don't understand how i can refresh the screen, sorry. This is from another app, the table is being overwritten by another table without the previous one clearing.

![screenshot-2019-03-16_20:46:28](https://user-images.githubusercontent.com/45419292/54480777-ee94c980-482c-11e9-8849-9ab6c46c801e.png)

**Comment by rivo** [comment]
I can't help you with the table without seeing the code for this. Please paste some code that will reproduce this issue.

Again, you don't need to call `app.Draw()` on each key event as it's called automatically by the main application loop. Unless you're making use of goroutines, you probably don't need to call `app.Draw()` anywhere at all. You can see in my code above that I'm not calling `app.Draw()`.

There's no minimum width for a table cell. The column width of a table is chosen based on the widest cell in that column. You could pad your cell's text with spaces if you want it to be wider than its contained text.

To answer your other questions, I need more specific information, preferably code.

**Comment by electronicous** [comment]
I'd say this is the most important part. The `startsearch()` function returns a `[]string`. Each two values need to be one next to another in two columns, which they are at the moment. But as mentioned, it's not clearing the screen from the previous table when new one comes.

```go
// Get terminal's size
g, _ := gocui.NewGui(gocui.OutputNormal)
maxW, maxH := g.Size()

// Start a new app
app := tview.NewApplication()

// Layout the widgets
grid := tview.NewGrid().
		SetBorders(true)

// Add an input field for the user input
inputField := tview.NewInputField().
			SetLabel(" Search for: ").
			SetFieldBackgroundColor(tcell.ColorDefault).
			SetFieldTextColor(tcell.ColorWhite).
			SetLabelColor(tcell.ColorWhite)	
inputField.SetBackgroundColor(tcell.ColorDefault)

// Table for the results
table := tview.NewTable().SetBorders(true)
table.SetBackgroundColor(tcell.ColorDefault)

// Iterating over the results
rows := len(startSearch(inputField.GetText()))
results := startSearch(inputField.GetText())

for row := 0; row < rows -1; row+=2 {
	table.SetCell(row, 0, tview.NewTableCell(results[row]).
								SetMaxWidth(maxW / 2))
	table.SetCell(row, 1, tview.NewTableCell(results[row + 1]).
								SetMaxWidth(maxW / 2))
}

// Remove the entered text once the search has been done
inputField.SetDoneFunc(func(key tcell.Key){
	inputField.SetText("")
	})

// Textview that changes on changed mode
textview := tview.NewTextView().
	SetDynamicColors(true).
	SetRegions(true).
	SetWordWrap(true).
	SetTextAlign(tview.AlignCenter).
	SetText(mode)
textview.SetBackgroundColor(tcell.ColorDefault)

// Handle keypress
app.SetInputCapture(func(event *tcell.EventKey) *tcell.EventKey {
	switch event.Key() {
		case tcell.KeyF1:
			switchmode(textview)
	}

	return event
})

// Position the widgets
// p primitive, row, column, rowSpan, colSpan, minGridHeight, minGridWidth, focus bool
grid.AddItem(inputField,   0,         1,          1, maxW - 21,  1,       30, true)
grid.AddItem(textview,     0, maxW - 18,          1,        17,  1,       12, false)
grid.AddItem(table,        2,          1, maxH - 30,  maxW - 2, 30, maxW - 1, false)	

// Error handling
if err := app.SetRoot(grid, true).SetFocus(grid).Run(); err != nil {
	panic(err)
}
```

**Comment by electronicous** [comment]
Can this one be reopened? I'm still having issues with this.

**Comment by rivo** [comment]
This issue kind of got lost. Apologies for that.

It seems that there's a misunderstanding regarding how `Grid.AddItem()` works. [Here's the documentation for it](https://godoc.org/github.com/rivo/tview#Grid.AddItem). And you might also want to check out the documentation for [`Grid.SetColumns()`](https://godoc.org/github.com/rivo/tview#Grid.SetColumns).

Grid rows and columns don't refer to the individual cells in a terminal window. A column can be multiple cells wide and a row can be multiple cells tall. In your example, let's assume that `maxW = 120`. Now you're telling `tview` that your table spans `maxW - 2 = 118` columns. Does your `Grid` layout really have that many columns? (Because you include borders, you must have a huge screen for that.)

I wouldn't be surprised that given these numbers, you are getting some weird effects.

First of all, I think you don't need `maxW` or `maxH` at all in your application. The idea of `tview` is to let you create layouts independently of the actual screen resolution. Without having tested it, this is probably what you want:

```go
// Position the widgets
// p primitive, row, column, rowSpan, colSpan, minGridHeight, minGridWidth, focus bool
grid.SetRows(1)
grid.AddItem(inputField, 0, 0, 1, 1, 0, 0, true)
grid.AddItem(textview, 0, 1, 1, 1, 0, 0, false)
grid.AddItem(table, 1, 0, 1, 2, 0, 0, false)
```

I'll reopen this again for a while in case you still have questions.

**Comment by electronicous** [comment]
I've given up on using tview for this project. Thanks still for letting me know on the fix.
