### ISSUE TITLE
Export ListItems for easier state control

### ISSUE THREAD

**Issue by diamondburned** [rivo/tview#297]
https://github.com/rivo/tview/blob/master/list.go#L25 could be exported along with `*listItem`s, I don't see why not. Being able to modify individual list entries make it easier to control the state for reactive UI.

**Comment by diamondburned** [comment]
P/S on an unrelated topic: I feel like a *lot* of the things in `tview` has no reasons to not be exported.

**Comment by rivo** [comment]
It's simple. Information hiding. I made a mistake already in exposing too much implementation and it limits my ability to add new features in some cases. But due to backwards compatibility, I'm not fixing that.

Maybe in the case of `listItem`, there is an opportunity to bring it in line with, say, `TreeNode`. But I want to see an actual problem from an actual application first where this would be the best solution.
