### ISSUE TITLE
ANSIWriter doesn't support SGR 2;37;0m

### ISSUE THREAD

**Issue by flw-cn** [rivo/tview#320]
`ANSIWriter` doesn't support SGR `ESC [2;37;0m`. This is a very popular sequence (sorry for can't give the standard which it follows).

**Comment by rivo** [comment]
This sequence is turned into  `[white::d]` which looks correct to me (2 = "faint (decreased intensity)", 37 = "foreground white"). I'm just not sure why the `0` is added as it is a reset code. Do you mean the fact that the background  colour is not reset? Can you elaborate  what you are  expecting here?

**Comment by flw-cn** [comment]
Thank you for your reply!

In my environment, `ESC [2;37;0m` resets the foreground and background color to normal color. I use iTerm2 on my MacBook. Here's what I see on my computer:

<img width="932" alt="image" src="https://user-images.githubusercontent.com/5546718/61178344-c459e980-a61d-11e9-8820-ce7c92d142e8.png">

In other environments I have used, like `putty/xshell`, they have similar display effects.

In fact, `tview` does not reset the background color when rendering this code, causing some applications that rely on this code to display errors, like this:

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/5546718/61178410-0cc5d700-a61f-11e9-8c5f-dbb5bbcad39a.png">

**Comment by dzpao** [comment]
In my environment, `ESC [2;37;0m` resets the foreground and background color to normal color. I use iTerm2 on my MacBook. Here's what I see on my computer:

<img width="932" alt="image" src="https://user-images.githubusercontent.com/5546718/61178344-c459e980-a61d-11e9-8820-ce7c92d142e8.png">

In other environments I have used, like `putty/xshell`, they have similar display effects.

In fact, `tview` does not reset the background color when rendering this code, causing some applications that rely on this code to display errors, like this:

![image](https://user-images.githubusercontent.com/52447680/61180308-fa5f9380-a646-11e9-9487-9af1e0a0dae1.png)

As can be seen from the above figure, the background color of the character on the right side of the portrait is contaminated. And below is the **expected effect**:

![image](https://user-images.githubusercontent.com/52447680/61180335-575b4980-a647-11e9-9644-1eb6494c0156.png)

In fact, in order to get the above effect, I not only processed `SGR 2;37;0m`, but also modified a piece of code related to bold attribute. If I don't process that bold attribute, I actually see something like this:
(some of the text marked as bold black(`SGR 1;30m`) is invisible):

![image](https://user-images.githubusercontent.com/52447680/61180444-f03e9480-a648-11e9-8e56-f79b008ec503.png)

**Comment by dzpao** [comment]
In order to figure out what happened when `2;37;0m`, I carefully studied the ANSI code, especially the CSI/SGR related specifications (I mainly rely on google.com and Wikipedia, and www.vt100.net), and iTerm2+zsh did the experiment, and I finally came up with the following points:

> * All properties are composed of only one number, except `38`/`48`
> * Any SGR attribute can appear with other attributes
> * Allows multiple attributes to be specified for text at once (such as blinking, bold, italic underlined, like this ***foo***)
> * Multiple attributes do not care about the order between each other, that is to say there is no fixed format (although it is customary to `properties; foreground color; background color` order)
> * The final visual effect is determined by the combined values of all the attributes. If a conflict is encountered, the attribute that appears later overrides the attribute that previously conflicted with it.

According to the above point of view, most of the code in `ansi.go` about SGR processing needs to be modified. include:
* `SGR 1` should be able to highlight the foreground color, similar to the effect of `SGR 90~97`.
* `SGR 21~27` should be able to properly close the corresponding properties set previously.
* `SGR 38/48` should not terminate `FieldLoop`, and should not be considered to have any code behind them.
* Added support for italics.

**Comment by rivo** [comment]
In your example, here is the part that I don't understand:

> some of the text marked as bold black(`SGR 1;30m`) is invisible

You have a black background. Why would you see any text if its foreground colour is also set to "black"? It should be invisible, shouldn't it? Are you sure this is a `SGR 1;30m` code?

**Comment by dzpao** [comment]
Thank you for your reply. I took a vacation last week and I didn't see your reply in time.

I understand what you mean. But in fact I have observed several popular terminal emulators, such as iTerm2 and Terminal.app, which both **render bold black to gray**.

> iTerm2
![image](https://user-images.githubusercontent.com/52447680/62202446-e5f7f680-b3bb-11e9-94ab-c190037bf6fc.png)

> Terminal.app
![image](https://user-images.githubusercontent.com/52447680/62202483-f3ad7c00-b3bb-11e9-954c-515863779a53.png)

So although I can't find the basis for doing so (except for one Chinese page on zh.wikipedia.org), I believe they do justifiably.

**Comment by rivo** [comment]
So I'm not sure if this was different before. But this sequence appears to be displayed correctly. Check this out:

```go
package main

import (
	"github.com/rivo/tview"
)

func main() {
	box := tview.NewBox().
		SetTitle(tview.TranslateANSI("\x1b[1;30;40mbold black")).
		SetBorder(true)
	if err := tview.NewApplication().SetRoot(box, true).Run(); err != nil {
		panic(err)
	}
}
```

This is what it looks like in iTerm:

![image](https://user-images.githubusercontent.com/480930/63949513-d3381680-ca7a-11e9-8c2b-9f22f3fe2ea8.png)

If you have some (brief) code that illustrates how it doesn't work in your case, please post it here.

**Comment by dzpao** [comment]
I tried the example you gave with the latest version of the code, and the effect is different from yours. It is not correct.

Below is the process of my testing.

![image](https://user-images.githubusercontent.com/52447680/64762130-26789180-d570-11e9-8a11-2d5e7d6b1d18.png)

**Comment by dzpao** [comment]
Here are two new cases to reveal the two bugs I just discovered:

```
Case 6.1: <ESC>[32mhello<ESC>[m world
Case 6.2: <ESC>[32mhello
    ...   world
```

![image](https://user-images.githubusercontent.com/52447680/64857108-379bce00-d656-11e9-90d8-57336c3c34cb.png)

In 6.1, `<ESC>[m` should be able to reset the current color attributes, but it doesn't.
In 6.2, the color attributes should affect the next line, but it doesn't.

**Comment by rivo** [comment]
I haven't had time yet to look at the details of your patch. But I've tried your code example. The "bold black" examples look the same directly in the terminal as well as in the application. The blinks also do. I tried iTerm2 and Terminal. There were differences in how these two terminal apps render the codes, though. Terminal actually renders "bold black" as black. You can hardly see it. And iTerm2 doesn't show blinking text but that's just my setting. Here's an example for iTerm2:

Direct:

![image](https://user-images.githubusercontent.com/480930/66995717-c2e20680-f0cf-11e9-97c8-27a8d9181493.png)

tview:

![image](https://user-images.githubusercontent.com/480930/66995747-cd9c9b80-f0cf-11e9-8fb1-d3b9670c4fd9.png)

There are some differences, though. Some of them are due to `tcell` requiring specific colours (there is no colour such as "use the terminal's default color", see also gdamore/tcell#292).

But the partial attribute reset is actually a bug which I need to fix. I hope to be able to resolve this soon.

**Comment by rivo** [comment]
Sorry it took so long. I believe the latest commit fixes these issues. Your test file looks like it's supposed to in `tview`. Let me know if there's anything else. (Probably best to open a new issue in that case so that the topic doesn't get lost.)
