### ISSUE TITLE
Weird bug with dynamic colors and word wrap true property

### ISSUE THREAD

**Issue by Bios-Marcel** [rivo/tview#335]
Hey,

When I have a `TextView` that has both `DynamicColors` and `WordWrap` on `true` and I use this code:

```go
package main

import "github.com/rivo/tview"

func main() {
	app := tview.NewApplication()
	text := tview.
		NewTextView().
		SetDynamicColors(true).
		//Comment in to see correct behaviour
		SetWordWrap(true).
		SetText("[black][:white] ")
	app.SetRoot(text, true)
	app.Run()
}
```

It will not apply the colors correctly.

However, if you now add another character behind the space, an `F` for example, it will behave correct.

**Comment by rivo** [comment]
Yes, this is because you set word-wrap to `true`. This will remove trailing spaces. When we word-wrap, trailing spaces in a line should not take up extra space. The last character of a word on a line should not be a space character. So we remove them.

If you call `SetWordWrap(false)`, your example will show the coloured space character.

**Comment by Bios-Marcel** [comment]
Hm, I see. That's a shame, since I intended using a space with changed background color as a fake cursor in oder to implement an editor.

**Comment by rivo** [comment]
I understand. Maybe you can use some kind of almost-empty character instead.
