### ISSUE TITLE
TableCell is not honoring Styles.PrimitiveBackgroundColor

### ISSUE THREAD

**Issue by dpotapov** [rivo/tview#35]
Hi,

Table cells are displayed with black background color by default. I think they should honor `Styles.PrimitiveBackgroundColor` setting.
![table](https://user-images.githubusercontent.com/5475708/35111278-88029e42-fc40-11e7-8805-f4e761209f42.png)

**Comment by rivo** [comment]
The nil value of `tcell.Color` is black. So since I introduced individual cell background colors, if you don't want to specify the background color for all cells, you now have to use the `NewTableCell()` constructor instead of instancing the `TableCell` type directly. The constructor will set the background color to `tcell.ColorDefault` which is transparent and the text color to `Styles.PrimaryTextColor`.

See also the documentation [here](https://godoc.org/github.com/rivo/tview#TableCell).

**Comment by dpotapov** [comment]
@rivo would it make sense to call the cell constructor from `SetCellSimple()` method?

**Comment by rivo** [comment]
Definitely! This was an oversight. Thanks for the hint. It's fixed now.

**Comment by dpotapov** [comment]
Great! thanks a lot!
