### ISSUE TITLE
Is it possible to make text not selectable by mouse?

### ISSUE THREAD

**Issue by jerblack** [rivo/tview#361]
I was looking through the demos and it appears that all mouse interactions can select the text, which makes for odd behavior with elements that are supposed to be acting like buttons or menus. Is it possible to disable text selection altogether while still leaving areas clickable and scrollable?

**Comment by rivo** [comment]
In the current version, this cannot be turned off. And for some terminals which don't support mouse input, this may never be available. There is an early issue #13 which requested mouse support as well as a recent PR #363 which I still need to evaluate. I can't comment on it because I haven't looked at it yet.

You might want to follow the discussion there.
