### ISSUE TITLE
Next node TreeView

### ISSUE THREAD

**Issue by xidod** [rivo/tview#432]
Hello, I'm missing something or is not possible from code go to the next or previous node in the TreeView?
I mean the same thing that arrow up and arrow down do.
For example, if I want every 5 seconds go to the next node from selected node, how I can do this?
We have [GetRowCount()](https://pkg.go.dev/github.com/rivo/tview?tab=doc#TreeView.GetRowCountl) and [GetScrollOffset](https://pkg.go.dev/github.com/rivo/tview?tab=doc#TreeView.GetScrollOffset) but not the list of the nodes.

**Comment by tslocum** [comment]
This is implemented in #437

**Comment by rivo** [comment]
@xidod `TreeView` is not a linear structure and while it internally (and temporarily) keeps a slice of visible nodes, this is not exposed to avoid users tampering with it. (And because it's temporary, there cannot be any guarantees for that slice.) Have you tried sending a key event to the tree view?

```go
treeView.InputHandler()(tcell.NewEventKey(tcell.KeyDown, 0, tcell.ModNone))
```

If this happens in a goroutine, you  should use `Application.QueueUpdateDraw()` (see the [Wiki](https://github.com/rivo/tview/wiki/Concurrency) for details).

I haven't tried this myself so it would be good to get some feedback from you. If this doesn't help, I may have to add the corresponding functions.

**Comment by xidod** [comment]
@rivo sure, i will try this and i give you a feedback asap

**Comment by xidod** [comment]
yes, i can go to the next node and previous node with ```tcell.NewEventKey(tcell.KeyDown,0,tcell.ModeNone)``` and ```tcell.NewEventKey(tcell.KeyUp,0,tcell.ModeNone)```
a little tricky but it works.

**Comment by rivo** [comment]
There is now a function `TreeView.Move()` that does this.
