### ISSUE TITLE
merging derailed/tview fork?

### ISSUE THREAD

**Issue by ghostsquad** [rivo/tview#460]
I noticed that https://github.com/derailed/k9s, a very popular tool is using a fork of this repo (https://github.com/rivo/tview/compare/master...derailed:master?ts=4) (`115 commits ahead, 75 commits behind rivo:master.`). I attempted to contact @derailed regarding whether the work they have done in their fork could be merged back into the official repo or not, but haven't received a response (email), and with no way to post an issue on their repo, here I am! I'm basically trying to figure out what I should be using for my own project, and what the overall health is of either.

**Comment by rivo** [comment]
I don't know all the forks out there and apart from a quick glance, I can't really comment on the fork you mentioned . Some changes they made look reasonable, others I probably wouldn't merge. I'm assuming that they needed changes/features quickly but because this repo doesn't progress very quickly, they decided to implement them in their own fork.

There are other forks out there that have added a lot of features (see #386 for a discussion). If you need those features and you're missing them here, it may be better to use that fork.

To me, simplicity, consistency, backwards compatibility, and few/no bugs is more important than adding all kinds of features which are only used by few people. Add to this the fact that I can only work on `tview` during my free time, of which I don't have a lot. So it's slow.

But I've said this before: I'm still working on it and plan on doing it for a long time. I don't want `tview` to become abandonware.

I'd say, if the existing features work for you, this repo is your best bet. If you're missing a lot of stuff and need it quickly, you may want to look elsewhere.

**Comment by ghostsquad** [comment]
> I'm still working on it and plan on doing it for a long time. I don't want tview to become abandonware.

❤️ 

Thank you! Ok, well I'm just getting started with all this, so this was just an initial "exploratory" concern. I'm happy to contribute to changes here. I prefer if features are added to the "primary" repo so that they can get the most benefit from the community. I'm likely not the _best_ person to help you maintain, but if you need help, I'd love to help!

**Comment by rivo** [comment]
Thanks. There are areas that need work but it would require longer discussions / exploration before any code is written. It's best not to just submit PRs (I don't have time to examine all the code that's been submitted to me) but instead to open an issue first to discuss the topic at hand. (Check out the [contributing guide](https://github.com/rivo/tview/blob/master/CONTRIBUTING.md) for details.)
