### ISSUE TITLE
TreeView button to jump up one level

### ISSUE THREAD

**Issue by SoMuchForSubtlety** [rivo/tview#489]
Would it be possible to bind left arrow / h to jump up one level in a TreeView? I can make a pull request if you approve.

**Comment by rivo** [comment]
I could probably add a new key binding to jump up one level. But it can't be "left arrow" because it's used for something else already. Maybe Ctrl-Left-Arrow (if that's possible). The question is also if that key binding should also cause all children to collapse or simply jump up without collapsing. Any thoughts?

**Comment by rivo** [comment]
If there's no further input regarding this topic, I will close this issue.

**Comment by SoMuchForSubtlety** [comment]
Sorry for the late response.

`KeyLeft` currently does the same thing as `KeyUp` in a TreeView, right? `Ctrl`+`KeyLeft` would also work. I assume making it possible to reassign the default key bindings to allow deeper customization would entail a large amount of work that is probably not worth the effort. 

For collapsing I would tend to say no, but that could maybe be a configurable setting?

**Comment by rivo** [comment]
I've added the "K" and "J" key binds to the `TreeView` which move you up and down the hierarchy, respectively. Unfortunately, there is no `CtrlKeyLeft` and using the key mod in `tcell` is apparently not reliable on all platforms.

But if you want to have your own key binds, you could use `SetInputCapture()` to translate them.
