### ISSUE TITLE
Horizonal scroll for List

### ISSUE THREAD

**Issue by abitrolly** [rivo/tview#512]
I want to add horizonal scrolling to the list element, because for wide tables not everything could fit the screen.

![image](https://user-images.githubusercontent.com/8781107/95545693-48f50c80-0a07-11eb-95e9-6b75ee35af60.png)

There is no setting for this on the List element https://pkg.go.dev/github.com/rivo/tview#List

What is the proper way to do this? An example in wiki would be nice to have.

**Comment by rivo** [comment]
@abitrolly It was previously not possible to shift list items horizontally. This is now implemented with the latest version. There are now `SetOffset()` and `GetOffset()` functions but I'm not sure if you need them because I also extended the function of the left and right arrow keys. Before hitting the right arrow key selects the next item (as it was before), it will shift the list to the left if it doesn't fit its box.

If this doesn't work as expected, please open a new issue so I don't miss it.
