### ISSUE TITLE
An example of how to use `Print` or `PrintSimple`

### ISSUE THREAD

**Issue by njones** [rivo/tview#52]
I'm trying to write some text into a `NewBox`, and I can't figure out how to do this. 

The documentation explains how `Print` is used to write to a box, but the function takes a `tcell.Screen` which is an interface the `Box` struct doesn't conform to. Maybe, the example of how to create and use a `Box` can be expanded to include some text as well?

**Comment by rivo** [comment]
Hi, `Box` by itself doesn't allow you to write text into it. It's really just a box with a border and a title and it's used as the superclass for all other primitives.

If you want to add text, you should use `TextView`. Because `TextView` implements the `io.Writer` interface, you can simply print to it:

```go
t := tview.NewTextView()
fmt.Fprintln(t, "Hello, World!")
```

The `Print()` functions in the package are used to write directly to a `tcell.Screen` but this is useful only if you decide to implement your own `Primitive` where you would implement the `Draw()` function. For most applications, this is probably not necessary.
