### ISSUE TITLE
Widgets inside a grid doesn't change focus when tab key is pressed

### ISSUE THREAD

**Issue by jcbritobr** [rivo/tview#555]
The code below has a problem that the bunttons inside the grid doesn't change or receive focus when tab key is pressed:

windows 10 64, golang 1.15.5_64

```go
package main

import (
	"github.com/rivo/tview"
)

func main() {
	app := tview.NewApplication()
	grid := tview.NewGrid().SetRows(3, 3, 3)
	grid.SetBorderPadding(2, 2, 2, 2)

	text := tview.NewTextView()
	text.SetText("initial text")
	button := tview.NewButton("Clique me").SetSelectedFunc(func() {
		app.Stop()
	})

	btn2 := tview.NewButton("Button 2")
	btn2.SetSelectedFunc(func() {
		text.SetText("buttton clicked")
	})

	grid.AddItem(button, 0, 0, 1, 1, 0, 0, true)
	grid.AddItem(btn2, 0, 1, 1, 1, 0, 0, false)
	grid.AddItem(text, 0, 2, 1, 1, 0, 0, false)

	if err := app.SetRoot(grid, true).Run(); err != nil {
		panic(err)
	}
}
```

I'm very new on tview, and I'm following the examples, but I think there are something wrong with this behavior.

![image](https://user-images.githubusercontent.com/6579862/105642147-b4ec6b00-5e66-11eb-8683-76e2429ebfd9.png)

**Comment by rivo** [comment]
Your first button has the current focus (you can see that because it's white) so it receives keyboard input. The Tab key is not bound to any action on the buttons, however, so nothing happens. You can use [`SetInputCapture()`](https://pkg.go.dev/github.com/rivo/tview#Box.SetInputCapture) to implement the desired action for the buttons.

Or if you really just want to have buttons in a horizontal layout, you could use `Form` with just buttons and no other fields. It implements button navigation with the Tab key.

Let me know if this helps.

**Comment by jcbritobr** [comment]
Hello. Thank you by the help. I1ll try here and will be back.
