### ISSUE TITLE
Display large texts

### ISSUE THREAD

**Issue by inmylo** [rivo/tview#565]
From the issues I see, that it is not recommended to use a `textView` to display large texts, especially with colors. For example: #451

Is there a fast & efficient way to display large texts? I could use terminal's native escape codes for colors.
There could be a way to simply display a scrollable text without any kind of parsing/processing, except mandatory things to not break a layout.

**Comment by rivo** [comment]
#451 was just updated. Does this help you?

Using escape codes won't help speed things up. `tview` is built on top of `tcell` which uses a buffer for the characters to be displayed on screen. While escape codes are used by `tcell` in the last step to sync that buffer with the screen, `tview` cannot bypass that buffer. So `TextView` will always use color tags to achieve colorization, which means parsing them etc.

Maybe writing a more efficient parser and keeping a better internal data structure for texts can help. But that's a big project and therefore in the far future (if at all). There are requests to add an editable widget (basically a text editor). I suppose that if I tackle that, I'll use the opportunity to think about how to deal with large texts there. (Good text editors are big projects by themselves, though, so that's a big "if".)

**Comment by inmylo** [comment]
No luck, I miss something probably. I've update `tview` and try:
```go
x := tview.NewTextView()
x.SetTextAlign(tview.AlignLeft)
x.SetMaxLines(10)
```
I check whether new method is added:
```go
grep "SetMaxLines" $GOPATH/src/github.com/rivo/tview/textview.go

// SetMaxLines sets the maximum number of lines for this text view. Lines at the
func (t *TextView) SetMaxLines(maxLines int) *TextView {
```
it means Yes. But when I try to compile the code I get:
```go
x.SetMaxLines undefined (type *tview.TextView has no field or method SetMaxLines)
```
Why?

**Comment by inmylo** [comment]
Looks good. At least RAM and CPU usage stays more or less the same
