### ISSUE TITLE
how to make this buttom menu in multilines when i resize the window?

### ISSUE THREAD

**Issue by supersensen** [rivo/tview#592]
![屏幕截图 2021-04-26 235501](https://user-images.githubusercontent.com/30255258/116113208-e0435800-a6ea-11eb-8dbd-d16d3dd0748c.png)
how to make this buttom menu in multilines when i resize the window? cheers

**Comment by rivo** [comment]
I didn't bother doing this in the demo because there is no automatic way to do it. I guess it could be done but it would probably complicate the demo code quite a bit. For these examples, I try to keep it simple.

If you have something similar in your application, maybe you could simply place it on two lines by default. Or, if you insist, you'll probably have to listen to draw events (with [`Application.SetBeforeDrawFunc()`](https://pkg.go.dev/github.com/rivo/tview#Application.SetBeforeDrawFunc)) and then adjust your `Flex` or `Grid` according to the current screen size.

**Comment by supersensen** [comment]
thank you
