### ISSUE TITLE
Request: Add ability to get done callback for input field in a form

### ISSUE THREAD

**Issue by mertzt89** [rivo/tview#60]
I noticed that it is currently only possible to get the "changed" callback from an input field that is part of a form. Would it be possible to make it so that it is also possible to get a done callback? 

I understand that it is necessary for the form to get a callback so that it can progress to the next field, so my thought would be that either the below snippet could be implemented to not override the "done" callback or have the done callback handler in the form perform an additional "done" callback after it does it's handling.

https://github.com/rivo/tview/blob/aea500559bc4bac320c43f380eb7451e3a72a0b7/inputfield.go#L170-L173

**Comment by rivo** [comment]
I guess the way to achieve this now would be to capture the input field's input with [`SetInputCapture()`](https://godoc.org/github.com/rivo/tview#Box.SetInputCapture). The four keys the `done` callback is called for are `tcell.KeyEnter`, `tcell.KeyTab`, `tcell.KeyBacktab`, `tcell.KeyEscape`.

I know this is not the exact solution you're proposing but like that, you wouldn't have to wait for me to fix this. (And it should probably be fixed in all `FormItem`'s.)

**Comment by mertzt89** [comment]
I just tested your suggestion and it is suits my needs. Thanks!
