### ISSUE TITLE
want a way to invalidate the screen

### ISSUE THREAD

**Issue by gdamore** [rivo/tview#603]
It's common to be able to force a redraw of the screen in apps with "Control-L" (this is a UNIXism).  The reason for this is that you might have other programs that have written to the screen in the background, and you want to clear the "damage".

Tcell offers an invalidation function for this (screen.Sync()) which basically tells tcell to ignore it's cached idea of the screen and assume it has to redraw everything from scratch.  (Obviously you don't want to do this often.)

I'd like this to be exposed -- ideally something like Application.Refresh() or ForceRefresh() or something. 

For now I can hack around it by calling Suspend() with an empty function.

(Btw, so far I'm finding tview is pretty nice -- I'm using it to build some other apps, so thanks for making it!)

**Comment by rivo** [comment]
Thanks! Glad you like it. (Now you know where all these weird requests of that @rivo guy are coming from, hehe.)

I had forgotten about `Screen.Sync()` and to be honest, in my tests, the screen was never corrupted. But it surely makes sense. I've included an `Application.Sync()` function now. I don't bind it to any key by default as I feel that's up to the users of the package to decide for themselves. (I'm familiar with <kbd>Ctrl-L</kbd> in `bash` but it simply clears the screen instead of syncing it.)

**Comment by gdamore** [comment]
Thanks.  CTRL- L is used my many many curses applications for this purpose.  Including vi. It has a long history of this usage. Bash doesn’t do more because it isn’t screen oriented.

Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________
