### ISSUE TITLE
Is there a way to make a box a "terminal view" ?

### ISSUE THREAD

**Issue by khepin** [rivo/tview#645]
I was trying to create a UI that would look something like:

```
------------ Info About Files In Sync To Server -------------
| detected file change                                      |
| uploading file to remote server                           |
| successfully uploaded                                     |
-------------------------------------------------------------
-------------- Bash Session On Remote Server ----------------
| welcome to remote server                                  |
| $> _                                                      |
|                                                           |
|                                                           |
|                                                           |
|                                                           |
|                                                           |
|                                                           |
|                                                           |
-------------------------------------------------------------
```
Where the top box is just information about detecting local file changes and syncing those upstream and the bottom one is a bash terminal / ssh session to said upstream. Something where the bottom window could receive an `stdin, stderr, stdout`.

At first glance I don't see a way to make something like this happen. Am I missing something?

**Comment by rgrannell1** [comment]
I believe this is possible, I'm doing something similar:

https://github.com/rgrannell1/rl/blob/f24ac01815571b17a4ba59906c7942a1bceb04e3/process.go#L45

- Create a `TextView` to hold terminal stderr, stdout output
- Execute an SSH connection using `exec.Cmd`, and redirect output to the TextView component writer
- You might need to play around with `/dev/tty` and handling / passing keystrokes through

Sorry about the vague answer, but I hope it helps

**Comment by khepin** [comment]
Yup, stdout, stderr I got alright indeed. The sticky part seems to be 
> play around with /dev/tty and handling / passing keystrokes through

**Comment by rgrannell1** [comment]
I figured; I would have been more exact if this was something I'd implemented (note I'm a user, not the package dev). My well-document cli [RL](https://github.com/rgrannell1/rl/blob/master/rl.go) does _most_ of what you're trying, so it might be a useful reference. It:

- Spins up the UI
- Uses tview listeners like `SetInputCapture` and `SetDoneFunc` and an `InputField` to capture user-entered text
- Stores this in a UI-wide state object
-  Launches a bash process (in `process.go:StartCommand)` based on TUI state and user-input, and intercepts output. It pipes `stdout` to a TextViewer

What I see as difficult in your case is working around

`Pseudo-terminal will not be allocated because stdin is not a terminal`

However you can force TTY use using `ssh -tt <ip>` which works for RL. SSH accepts commands from `stdin` so 

```bash
echo "ls" | ssh -tt <ip>
```
Run from `exec.Cmd` will achieve what you want. For example, when I run this command from RL it SSH's into my `multipass` VM, runs commands like list (awkwardly, rl is not an SSH client really) and returns standard-output (only for my app) to a textview component. It even renders `catimg` images correctly!

![Screenshot from 2021-09-14 14-06-10](https://user-images.githubusercontent.com/835618/133262972-7e477b7c-590a-4636-ab88-aa8ddfc887bc.png)

I hope this helps, reach out via this ticket (if the package-owner doesn't object) and I'll try to help

**Comment by khepin** [comment]
I think I was able to approach my goal using https://github.com/creack/pty

But capturing STDIN and io.Copy-ing it to a TextView seems to suffer from a lot of performance drag and characters are missed out entirely. The same code outside of a TextView, using a buffer or stdout as the place to write works "just fine™".

If I could figure out the perf issue there, then the remaining piece would be figuring out how control sequences are sent. That doesn't seem to work with the PTY based solution I tried so far.

**Comment by khepin** [comment]
Also, thanks, I'll dig into `SetInputCapture` and your CLI today if I can.

**Comment by rgrannell1** [comment]
one gotcha I spent a lot of time root-causing. When commands are run non-interactively, they may buffer output and not work as expected (for me, grep would not output). You may need to use the `stdbuf` and `unbuffer` shell commands (or a Golang equivalent) if you run into similar issues

**Comment by rivo** [comment]
@khepin You'll definitely get a performance hit. Characters from the external application will be stored in a buffer, that buffer will be formatted to fit the `TextView`, the resulting characters will be saved to a `tcell` screen buffer, and `tcell` will then output Escape sequences to your terminal. If you use [`ANSIWriter`](https://pkg.go.dev/github.com/rivo/tview#ANSIWriter), e.g. for coloured output, then there is even one more step.

But that's just due to the architecture of the whole project. There's no way to bypass this (except by [suspending](https://pkg.go.dev/github.com/rivo/tview#Application.Suspend) the application temporarily). What you can do, however, is to space out your `TextView` redraws so the steps above don't happen after each character sent by your application.

**Comment by khepin** [comment]
Yup, this was using an ANSIWriter. I'll see if I can give a shot at spacing the `TextView` redraws a bit more and if that helps enough.

**Comment by tedsmitt** [comment]
@khepin did you ever find a solution to this? Would like to achieve the same functionality!

**Comment by khepin** [comment]
Nope, I stopped working on what I needed it for too so I don't have much to offer.
