### ISSUE TITLE
table scrolling wraps now?

### ISSUE THREAD

**Issue by toffaletti** [rivo/tview#656]
I updated to latest commit, implemented TableContent interface, and now I see this new behavior:

- page down stops at end of table (like before)
- page up does not stop, but wraps back to the bottom so you can infinitely loop top to bottom using page up.
- single step scrolling also wraps in both directions

**Comment by rivo** [comment]
Yes, that's true. Before this merge, it only wrapped in one direction which was quite inconsistent. I.e. you could move right and end up on the next line but if you moved left, you wouldn't be sent back. So that was unexpected and, in my opinion, undesirable.

If this is a problem in your application, please elaborate a bit why.

**Comment by rivo** [comment]
Yes, that's true. Before this merge, it only wrapped in one direction which was quite inconsistent. I.e. you could move right and end up on the next line but if you moved left, you wouldn't be sent back. So that was unexpected and, in my opinion, undesirable.

If this is a problem in your application, please elaborate a bit why.

**Comment by rivo** [comment]
Yes, that's true. Before this merge, it only wrapped in one direction which was quite inconsistent. I.e. you could move right and end up on the next line but if you moved left, you wouldn't be sent back. So that was unexpected and, in my opinion, undesirable.

If this is a problem in your application, please elaborate a bit why.

**Comment by toffaletti** [comment]
It would be nice to have control over the behavior. In my case, holding page up to get back to the top of the table and have it stop was a desirable behavior because there are many pages and you might be in the middle somewhere and want to quickly get to the top. Now it just keeps wrapping to the bottom though.

**Comment by rivo** [comment]
Makes sense. (Although pressing <kbd>g</kbd> / <kbd>G</kbd> will move the selection to the beginning / end.)

The latest commit introduces a way to control wrapping behaviour. After some consideration, I decided that the default should be that there is no wrapping. (I was never quite happy with the previous implementations.)
