### ISSUE TITLE
When mouse enabled - text is not selectable on app

### ISSUE THREAD

**Issue by buzzdan** [rivo/tview#694]
I would like to have text selection enabled on my app (any text - from a table, text view, etc...)
the problem is when i enable mouse on the app, text selection turns off.
i couldn't find any way to enable it
am i missing something?

any help would be highly appreciated 🙏

**Comment by rivo** [comment]
To my knowledge, you can't have both. When mouse handling is enabled, your terminal sends all mouse events to the app instead of processing them itself, e.g. for text selection.

**Comment by buzzdan** [comment]
mmm i see what you are saying, but still i wonder how other TUI apps work?
as a user i'm used to it that mouse selection is enabled

**Comment by rivo** [comment]
I can only guess (also because I haven't seen any TUI apps that enable both; they probably exist but I haven't used any yet) that the selection is built into the app itself. Some kind of drag and drop functionality which highlights selected text and then interacts with the OS's clipboard.

You could try to do that yourself (e.g. using region tags in `TextView`) but I'm not sure how difficult it would be.
