### ISSUE TITLE
Editable DropDowns

### ISSUE THREAD

**Issue by muesli** [rivo/tview#77]
Essentially a combination of an InputField and a DropDown: let the user enter a custom text or pick an item from the DropDown list (the address bar in your browser would be an example of such a UI widget).

**Comment by rivo** [comment]
So, generally, I understand what you want here. (And I would probably describe this as some kind of "autocomplete" functionality for `InputField` primitives.) Is this something that you currently require in an application you're developing? Or is it just a general idea that you had?

**Comment by muesli** [comment]
Besides being a fairly common and convenient UI component, I'm actually writing a little systemd service manager (https://github.com/muesli/service-tools) which would directly benefit from such a feature.

**Comment by rivo** [comment]
So there are two solutions I can think about:

1. Extending the `DropDown` component so that you can enter text. This text will only be used to find a matching option in the drop-down list (the ones which have your entered text as a prefix). This basically helps the user jump to the desired option quickly.
2. Adding "autocomplete" functionality to the `InputField`. When the user enters text, a callback function is invoked which returns a list of matches. Those matches are then shown in a drop-down list and the user can choose from that list (using the up and down arrow keys).

In the first solution, you can still only select from the options defined from the start. In the second solution, the user may choose to ignore the options presented to them and instead type whatever they want.

So these are different ideas. Let me know which one you are looking for in your application.

**Comment by muesli** [comment]
I think both solutions would be nice additions to tview's behavior.

Regarding
1. It would probably be enough to select/jump to the matching item when a user starts typing.
2. I like the callback idea a lot (this is probably the feature I'd currently need the most)

**Comment by rivo** [comment]
Ok. So the `DropDown` primitive now allows you to type to directly jump to matching options.

Autocomplete in `InputField` will take a bit more effort. Not sure if I will have this very soon.

**Comment by mikeschinkel** [comment]
Hi @rivo I need to be able to present several items that users can choose from and **either** allow them to select from them, or be able to enter custom values. I have numerous fields that need this but one example is a software version number where I have a list of released version numbers but the user may actually be using a beta version where the version number is not released.

I am willing to help with the autocomplete, as you have probably seen my recent flurry of PRs, but as that would be a bit more complex I would want input from you as to how you would prefer it to be implemented.
