### ISSUE TITLE
[QUESTION] Textarea - How to color some words like textview?

### ISSUE THREAD

**Issue by rsmaximiliano** [rivo/tview#783]
Hi, I want to know if is possible to color some words when user is typing words in a Textarea

**Comment by rivo** [comment]
No, it's not possible. I collected feedback for the `TextArea` for over a year (see #594) and it was decided that coloring was "not necessary / required". To be honest, I'm glad about that because the text area is already very complex, coloring / syntax highlighting would have made it almost unmaintainable.

**Comment by rsmaximiliano** [comment]
Ok! Thank you for your time and work <3
