### ISSUE TITLE
Override themes for application individually

### ISSUE THREAD

**Issue by IvanKorchmit** [rivo/tview#868]
Hello, I want to say right away that the package is fantastic and well-done! 
However, there's one quirk that I hope will be fixed in a new version.

The only limitation I encountered while using this package is styling, I am making a networked application which can use several instances of `tview.Application` and since `tview.Styles` is a global variable shared among other primitives, I can't really personalize the theme for each session.

The wiki didn't mention any style overriding (i.e. passing Theme struct as the parameter at very least).

![image](https://github.com/rivo/tview/assets/70683749/4eb3019a-cc63-40c5-960a-474ee3556190)
In this screenshot you can see default theme being used.

![image](https://github.com/rivo/tview/assets/70683749/06fe25f5-5eae-47e4-a2bf-72c0d307ea26)
When I execute this command, it is supposed to change theme at the current session by idea, however when somebody else joins, then the new theme is applied on that session.
![image](https://github.com/rivo/tview/assets/70683749/a076eb4e-9882-4d9b-92e8-d2b81cc8f3ec)

```go
func applyTheme() {
	tview.Styles.BorderColor = tcell.ColorMaroon
	tview.Styles.PrimaryTextColor = tcell.ColorGold
	tview.Styles.PrimitiveBackgroundColor = tcell.ColorLightGreen
}
```
The code in question

**Comment by digitallyserviced** [comment]
Maybe this could get you partly where you want to go...

This is something I had come up with to handle storing theme/style info in an external file. It could easily be hacked up to add a way to pull styles/themes from specific sources based on certain criteria. 

Rather than rely on all your primitives pulling from the global `Theme`, apply styles to them using my theming thing here... Pull styles by name that can be differentiated by that, or by some additional criteria that is passed along and return something different.

The theming repo is mainly a registry for styles, and format strings that can be pulled and defined by name. 

If you pair this with my fork of tview, you can also define `borderStyle` per `Box` and also for the `[fg:bg:attr]` style tags my `Styler` can be set globally, or per `TextArea` which will allow you to define style tags such as `[titleBold]` instead. Again, this will pull them from my theme registry thing here, and you can change how it chooses what styles to return. I am sorry I do not have any decent example code or anything just yet. But hopefully you can get the gist..

### my theming registry deal...
https://github.com/digitallyserviced/tview-theming

### the Styler functions you can define globally to hook into the style returned during `[tag]` styling
https://github.com/digitallyserviced/tview/blob/611a26b9bad195005135a6ce0215280c68d57903/util.go#L94

### the `TextView` styler hooking to have specific textview stylers
https://github.com/digitallyserviced/tview/blob/611a26b9bad195005135a6ce0215280c68d57903/textview.go#L383

### and the whole fork with all sorts of extra shit
https://github.com/digitallyserviced/tview/tree/digitally

**Comment by rivo** [comment]
@IvanKorchmit You are correct. The way it currently works is that there is only one global theme which would apply to all applications if you used multiple. (I'm curious how you use multiple instances of `Application`, I have never seen that before.)

I have plans to allow for more detailed styling but as of now, I can't say when this will be available.

I'm closing this issue for now. If you feel that you need more help, please comment here or open a new issue.

**Comment by IvanKorchmit** [comment]
> @IvanKorchmit You are correct. The way it currently works is that there is only one global theme which would apply to all applications if you used multiple. (I'm curious how you use multiple instances of `Application`, I have never seen that before.)
> 
> I have plans to allow for more detailed styling but as of now, I can't say when this will be available.
> 
> I'm closing this issue for now. If you feel that you need more help, please comment here or open a new issue.

Hello, I'm using `tview` for multi-user dungeon framework via SSH and each session creates `Application` instance which is where it is used for rendering UI. I was curious to implement something like themes for different rooms (entering dungeon would result in a dark or gray themed UI for better experience)

**Comment by rivo** [comment]
Got it. Interesting. Well, as mentioned, this is currently not supported but there may be tools to facilitate this soon. (Again, I don't know how "soon".)

If you really need it, short of patching `tview`, you could think about starting separate processes for each session. But I don't know how complicated this is in your application.

**Comment by IvanKorchmit** [comment]
Well, I'm totally fine, it would be nice to have that. I can definitely
live without that!
