### ISSUE TITLE
DoubleClickInterval could be improved by taking into account last click position

### ISSUE THREAD

**Issue by carpii** [rivo/tview#872]
I have a table and click different rows with the mouse, but it does not always select the clicked row

This appears to be due to `tview.DoubleClickInterval` which will interpret any two clicks within 500ms to be a double-click
I can reduce this value, to make clicks more responsive, but then it makes it more difficult to intentionally double-click

Im wondering if its possible for tview to record the position of the first click, and then only consider a second click to be a double-click if its within a certain proximity to the first click?

This would allow us to keep `tview.DoubleClickInterval` interval at 500ms, but if you click in a different area it would always be interpreted as a click?

**Comment by digitallyserviced** [comment]
This is just one of those things that in all honesty is not well suited for a terminal environment. Using a mouse in a terminal has been a third-class citizen for nearly 30 years. 

Might I suggest maybe instead of double-clicking and handling that, add a modifier (ctrl,shift,alt) and single-click if you really want to use the mouse?

With that said however there are better ways to handle this I believe. The idea with this suggestion is that your clicks will always be on/within the component you intend to target, regardless of the difference in positions, and as long as the last click is within the component/target.

I will again point at my fork which has a method for `GetComponentAt` for querying the layout/primitives and returning what component/primitive is at that location.

```go
// GetComponentAt returns the highest level component at the given coordinates
// or zero if no component can be found.
func (a *Application) GetComponentAt(x, y int) *Primitive {
    return getComponentAtRecursively(a.root, x, y, a)
}
```

In your mouse handler, use the x,y and a reference to the root tview.Application to query for it.

https://github.com/digitallyserviced/tview/blob/611a26b9bad195005135a6ce0215280c68d57903/application.go#L734-L739

**Comment by carpii** [comment]
Thanks @digitallyserviced

I appreciate mouse in terminal is never going to be ideal, but tview does a reasonable job of it so far. 
A page in my app typically has several frames dynamically created controls, so mouse is very convenient whilst testing

Regarding your branch, you seem to have made a bunch of useful additions. 
I wonder if you have considered isolating these changes and suggesting them as a PR?

Cheers

**Comment by digitallyserviced** [comment]
@carpii 

> Regarding your branch, you seem to have made a bunch of useful additions.
> I wonder if you have considered isolating these changes and suggesting them as a PR?

So, to be honest, the fork that I have actually pushed to a public repo is a mess and lacking any sort of proper public release In many ways...

- the only included files are the ones that were there originally. and then my changes replaced those files.
- it does not include any ***new*** files i've added that did not exist in `tview` at time I pushed it
- you need my changes to tcell `gdamore/tcell` that has extra helpers, and better paste handling from `zyedidia/tcell`
- it severely lacks proper organization, documentation, and updated demos/examples
- a rebase probably to pull in @rivo 's latest master branch
- other misc breaking API changes
- default borders are somewhat broken without using my defined `borderStyle`'s which change how they are drawn (1/8 block elements instead of box drawing so the lines are flush instead of centered in cell) 

you can probably even see references to `AnimatedPrimitive` and the theme/styler hooks.

What I will probably end up doing, is taking the project i had been playing with for a while, and actually polish it a bit. 

the project would need to include ALL the different changes/forks of whatnot i had hacked at to get what i needed done.

A small teaser as to what I have been building using `tview`

![demo-nvim-script](https://github.com/rivo/tview/assets/1828125/c438ea8c-b57c-413f-b2ed-b50a1445475d)

List of widgets/features I've created and somewhat seen in the gif:

- Animation
- Stack based UI, push views onto stack, pop them off
- Revamped input handling, similar to JS/browser with current view handling, or bubbling event to next in stack
- Toolbar Manager
- color picker
- swatch/color selector
- V8 engine for JS. plugin system for handling tables/lists and other widgets
- better list widget
- better table widgets (with JS API) 
- carousel 
- tdfgo rendering
-

**Comment by digitallyserviced** [comment]
@carpii also re: your PR for the getpages...
my fork allows for page views to implement an interface for handling events...

```go
const(
  Front PageChangeType = iota
  Back
  Refresh
  Removed
  Drawn
 Focused 
)

type Paged interface {
  Name() string
  Shown(*Pages)
  Hidden(*Pages)
  Changed(*Page, *Pages, PageChangeType)
}
```

**Comment by carpii** [comment]
Hiya @digitallyserviced

Thanks for the help so far. 
Looks like you've done some awesome work on your fork, with lots of new features

The project I'm working on right now is fairly long-term, and likely to become a mature project over time. 
I'm a little reluctant to switch to an undocumented fork right now, at least until I find some major show-stoppers where I have no other choice.

> So, to be honest, the fork that I have actually pushed to a public repo is a mess and lacking any sort of proper public release In many ways...

Yeah, I understand. I'm guessing it developed over time for your own needs, and was never intended to be a public fork

**Comment by digitallyserviced** [comment]
@carpii 
No problem, again hit me up on twitter/discord if you want to discuss, or want some insight into my thoughts/wtf coding....

To be honest. There are many features that I pulled out of the open PR's that are just stale. 
t
I used useful-forks to find active/ahead commits to this repo, and cherry-picked from the numerous additions/changes/features people have added to their own forks. So mine is a culmination of all those others, and my own additions.

if you look through the PR's you will notice a ton from a `tslocum`. All his additions/features he impld in his fork `tslocum/cview` he provided as PR's. 

It seems `cview` came about because of the lack of movement on this repo feature-wise and for thread safety.

I understand the not havin time for things, but maybe I can see about @rivo delegating or adding collab's to handle some of the things that he doesn't have the time for so we can possibly breathe a bit more life into what is possible with `tview` (as you can see from some of my projects).

There are plenty of things though, that I believe are missing from the current feature set of what is considered to be vanilla `tview`. Or there are patterns/concepts that are not able to come to fruition without hacking into the core, or coming up with monkeypatched workarounds.

 I am interested to hear more about your project, and if I could help at all.

I understand not wanting to deal with an undocumented fork. But I als understand what comes from working with frameworks that ***almost*** give you all the options you need.

Instead of thinking about it like using an "undocumented fork", and think of it more as working with "a fork you have molded to work for your use case, that you have yet to document". whether or not there is documentation shouldnt affect whether or not it is valuable to your uses.

Rememeber, I didnt just work with zero documentation for what I needed, I worked with a framework that didnt even have the things I ***needed*** to build what I wanted. it all comes down to the ability to be comfortable with the code you use, yours, libraries, someone elses, AI generated, w/e

**Comment by carpii** [comment]
Thanks for the reply. I'll close this ticket, as clearly DoubleClickInterval is not the elegant solution I initially thought it was

So my reason for wanting to stick with the official fork (for now) is mostly due to risk management.
@rivo has a long history of maintaining tview, and whilst there's lots of forks, many of them end up abandoned (the `cview` fork you mentioned seems to have been abandoned a couple of years ago, unless I'm mistaken).

So I'd prefer not to build an app on top of a more feature-rich fork, if itmeans I'm more likely to end up painting myself into an unmaintained corner a few years down the line.

I may end up creating my own fork, but I'd prefer to be familiar with each downstream change, rather than just migrate to a heavily modified fork. 

> I am interested to hear more about your project, and if I could help at all.

It's primarily an accounting app, aimed at personal, freelancers, and SOHO usage.
MySQL backed, but with an emphasis on automated rule-based OFX/QIF/CV imports for its transaction source, plus a JSON-based CLI interface for batch processing, categorising, reporting etc. 

Later versions may include a REST API and web frontend using the same backend JSON API, plus investment tracking. 
I need this software for my own use, but whether it evolves beyond what I need, we'll see :-)
